
import turtle

screen = turtle.screen()
screen.screensize(500,500)
screen.bgcolor('lightblue1')

t = turtle.Turle()
t.speed(0)
# #water
t.penup()
t.goto(-5000,80)
t.pendown()
t.fillcolor('dodgerblue4')
t.pencolor('dodgerblue4')
t.begain_fill()
t.goto(5000,0)
t.goto(5000,-150)
t.goto(-5000,-150)
t.goto(-5000,0)
t.end_fill()
#sand
t.penup()
t.goto(-5000,-50)
t.pendown()
t.fillcolor('tan')
t.pencolor('tan')
t.begin_fill()
t.goto(5000,-100)
t.goto(5000,-5000)
t.goto(-5000,-5000)
t.goto(-5000,-50)
t.end_fill()

t.penup()
t.goto(-200,250)
t.pendown()
t,pencolor('yellow')
t.begin_fill()
t.fillcolor('yellow')
t.begin_fill()
t.circle(50)
t.setheading(270)
t.end_fill()

t.penup()
t.goto(200,-250)
t.pendown()
t.pencolor('pink')
t.fillcolor('pink')
t.begin_fill()
t.left(90)
t.forward(100)
t.left(90)
t.forward(150)
t.left(90)
t.forward(100)
t.left(90)
t.forward(150)
t.end_fill()

#umbrellastick
t.penup()
t.goto(-220,-175)
t.pendown()
t.fillcolor('gray')
t.pencolor('gray')
t.begin_fill()
t.goto(-220,-350)
t.goto(-210,-350)
t.goto(-210,-175)
t.goto(-220,-175)
t.end_fill()

#umbrellatop
t.penup()
t.goto(-117,-225)
t.pendown()
t.fillcolor('purple')
t.pencolor('purple')
t.setheading(90)
t.begin_fill()
t.circle(95,180)
t.end_fill()


t.penup()
t.goto(0,-200)
t.pendown()
t.pensize(8)
t.penccolor('gray')
t.setheading(90)
t.circle(40,180)
t.begin_fill()
t.fillcolor('red')
t.pencolor('red')
t.pensize(8)
t.goto(-80,-200)
t.goto(0,-200)
t.pensize(5)
t.goto(-10,-280)
#t.goto(0,-300)
t.goto(-70,-280)
t.goto(-80,-200)
t.end_fill()

t.penup()
t.goto(0,0)
t.pendown()
t.setheading(270)
t.fillcolor('tan3')
t.pencolor('tan3')
t.begin_fill()
t.circle(25,180)
t.end_fill()
t.setheading(0)
t.penup()
t.goto(25,0)
t.pendown()
t.begin_fill()
t.goto(-50,0)
t.goto(-50,-25)
t.goto(25,-25)
t.goto(25,0)
t.end_fill()


t.penup()
t.goto(100,-50)
t.pendown()
t.fillcolor('grey')
t.pencolor('grey')
t.begin_fill()
t.goto(125,-50)
t.goto(100,-25)
t.goto(100,-50)
t.end_fill()


t.penup()
t.goto(-250,-25)
t.pendown()
t.pencolor('red')
t.begin_fill()
t.fillcolor('red')
t.begin_fill()
t.circle(25)
t.setheading(270)
t.end_fill()
t.pencolor('red')

t.penup()
t.goto(-260,0)
t.pendown()
t.pencolor('dodgerblue4')
t.begin_fill()
t.fillcolor('dodgerblue4')
t.begin_fill()
t.circle(10)
t.setheading(270)
t.end_fill()
t.pencolor('dodgerblue4')

#cloud
t.penup()
t.goto(50,230)
t.pendown()
t.fillcolor('white')
t.pencolor('white')
t.begin_fill()
t.goto(50,300)
t.goto(250,300)
t.goto(250,230)
t.goto(50,230)
t.end_fill()
#1st circle of the clouds
t.penup()
t.goto(35,258)
t.pendown()
t.fillcolor('white')
t.fillcolor('white')
t.begin_fill()
t.circle(30)
t.end_fill()
#2nd circle of the clouds
t.penup()
t.goto(45,290)
t.pendown()
t.fillcolor('white')
t.pencolor('white')
t.begin_fill()
t.circle(30)
t.end_fill()
#3rd circle of the clouds
t.penup()
t.goto(78,300)
t.pendown()
t.fillcolor('white')
t.pencolor('white')
t.begin_fill()
t.circle(30)
t.end_fill()
#4th circle of the clouds
t.penup()
t.goto(110,305)
t.pendown()
t.fillcolor('white')
t.pencolor('white')
t.begin_fill()
t.circle(30)
t.end_fill()
#5th circle of the clouds
t.penup()
t.goto(140,310)
t.pendown()
t.fillcolor('white')
t.pencolor('white')
t.begin_fill()
t.circle(30)
t.end_fill()
#6th circle of the clouds
t.penup()
t.goto(175,305)
t.pendown()
t.fillcolor('white')
t.pencolor('white')
t.begin_fill()
t.circle(30)
t.end_fill()
#7th circle of the clouds
t.penup()
t.goto(205,295)
t.pendown()
t.fillcolor('white')
t.pencolor('white')
t.begin_fill()
t.circle(30)
t.end_fill()
#8th circle of the clouds
t.penup()
t.goto(225,262)
t.pendown()
t.fillcolor('white')
t.pencolor('white')
t.begin_fill()
t.circle(30)
t.end_fill()

t.penup()
t.goto(0,50)
t.pendown()
t.pencolor('black')
t.write('happy summer', font=("arial", 24, "bold"))



turtle.done()

